version: 2

before:
  hooks:
    - sh -c "cd gophertype && go mod tidy"
    - sh -c "cd gophertype && go mod download"

builds:
  - id: gophertype
    dir: gophertype
    main: .
    binary: gophertype
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: gophertype
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - gophertype/README.md

blobs:
  - provider: s3
    bucket: zootype
    region: auto
    endpoint: https://{{ .Env.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
    directory: "releases/{{ .Version }}"
    extra_files:
      - glob: ./dist/*.tar.gz

brews:
  - repository:
      owner: treygilliland
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/treygilliland/zootype
    description: "Terminal-based typing practice tool with real-time WPM and accuracy tracking"
    license: MIT
    url_template: "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/{{ .Version }}/{{ .ArtifactName }}"
    install: |
      bin.install "gophertype"
    test: |
      system "#{bin}/gophertype", "--version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: treygilliland
    name: zootype
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
